// This file is generated by scripts/fetch-treesitter-grammars.ts. Do not edit manually.
// Run `bun run fetch:treesitter-grammars` to refresh vendored assets.

import { fileURLToPath } from "node:url"

import type { FiletypeParserOptions } from "@opentui/core"

const sqlHighlights = fileURLToPath(new URL("./assets/sql/highlights.scm", import.meta.url))
const sqlLanguage = fileURLToPath(new URL("./assets/sql/tree-sitter-sql.wasm", import.meta.url))

let cachedParsers: FiletypeParserOptions[] | undefined

export function getTreeSitterParsers(): FiletypeParserOptions[] {
  if (!cachedParsers) {
    cachedParsers = [
      {
        filetype: "sql",
        queries: {
          highlights: [sqlHighlights],
        },
        wasm: sqlLanguage,
      },
    ]
  }

  return cachedParsers
}
